import { socialLinks } from "@/components/Contact/contactData";

/** Production site URL — override with SITE_URL or NEXT_PUBLIC_SITE_URL in env. */
export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ??
  process.env.SITE_URL ??
  "https://kartikkoul.com";

export const siteConfig = {
  url: siteUrl.replace(/\/$/, ""),
  name: "Kartik Koul",
  title: "Kartik Koul | Software Engineer",
  shortTitle: "Kartik Koul",
  description:
    "Software engineer turning ideas into scalable full-stack and AI-powered products.",
  jobTitle: "Software Engineer",
  locale: "en_US",
  twitterHandle: "@kkwhocodes",
  ogImageAlt: "Kartik Koul — Software Engineer",
  keywords: [
    "Kartik Koul",
    "Kartik",
    "Software Engineer",
    "Full Stack Developer",
    "Full Stack Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Web Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "MERN Stack Developer",
    "AI Engineer",
    "AI Developer",
    "Generative AI",
    "LLM Applications",
    "RAG",
    "Retrieval Augmented Generation",
    "AI-powered Apps",
    "OpenAI",
    "LangChain",
    "Vector Databases",
    "Prompt Engineering",
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "Tailwind CSS",
    "Firebase",
    "REST API",
    "GraphQL",
    "Prisma",
    "Docker",
    "AWS",
    "Vercel",
    "GitHub",
    "Portfolio",
    "Developer Portfolio",
    "Software Developer Portfolio",
    "Full Stack Portfolio",
    "AI Portfolio",
    "Freelance Developer",
    "Freelance Software Engineer",
    "Startup Engineer",
    "Web Applications",
    "Scalable Applications",
    "Modern Web Development",
  ],
  sameAs: socialLinks.map((link) => link.href),
} as const;
